version: "3"

services:

  # Nginx
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: docker-nginx
    ports:
      - "${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}"
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw   
    restart: always
    links:
      - php-fpm:php-fpm
    networks:
      - default  

  # PHP-FPM    
  php-fpm:
    image: php:${PHP_VERSION}
    container_name: docker-php
    ports:
      - "${PHP_FPM_PORT}"
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always  
    networks:
      - default

  # MySQL
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: docker-mysql
    ports:
      - "${MYSQL_HOST_PORT}"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw      
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro  
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    networks: 
      - default  

  # Redis
  redis:
    image: redis:${REDIS_VERSION}
    container_name: docker-redis
    ports:
      - "${REDIS_HOST_PORT}"
    volumes:
      - ${REDIS_DATA_DIR}:/data:rw
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks: 
      - default  

# Networks      
networks:
  default: