version: '3'

services:

  # 主节点一号
  redis-cluster-1:
    image: redis:5-alpine
    container_name: redis-cluster-master-1
    ports:
      - 6401:6379
    volumes:
      - ./database/redis-cluster-1:/data
      - ./conf/redis-cluster-1/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    networks: 
      - sentinel-master-slave

  # 主节点二号
  redis-cluster-2:
    image: redis:5-alpine
    container_name: redis-cluster-master-2
    ports:
      - 6402:6379
    volumes:
      - ./database/redis-cluster-2:/data
      - ./conf/redis-cluster-2/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    networks: 
      - sentinel-master-slave
                 
  # 主节点三号
  redis-cluster-3:
    image: redis:5-alpine
    container_name: redis-cluster-master-3
    ports:
      - 6403:6379
    volumes:
      - ./database/redis-cluster-3:/data
      - ./conf/redis-cluster-3/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    networks: 
      - sentinel-master-slave

  # 从节点一号
  redis-cluster-4:
    image: redis:5-alpine
    container_name: redis-cluster-slave-1
    ports:
      - 6404:6379
    volumes:
      - ./database/redis-cluster-4:/data
      - ./conf/redis-cluster-4/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf','--slaveof', 'redis-cluster-master-1', '6379']
    restart: always
    depends_on:
      - redis-cluster-1
    networks: 
      - sentinel-master-slave

  # 从节点二号
  redis-cluster-5:
    image: redis:5-alpine
    container_name: redis-cluster-slave-2
    ports:
      - 6405:6379
    volumes:
      - ./database/redis-cluster-5:/data
      - ./conf/redis-cluster-5/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf','--slaveof', 'redis-cluster-master-2', '6379']
    restart: always
    depends_on:
      - redis-cluster-2
    networks: 
      - sentinel-master-slave      

  # 从节点三号
  redis-cluster-6:
    image: redis:5-alpine
    container_name: redis-cluster-slave-3
    ports:
      - 6406:6379
    volumes:
      - ./database/redis-cluster-6:/data
      - ./conf/redis-cluster-6/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf','--slaveof', 'redis-cluster-master-3', '6379']
    restart: always
    depends_on:
      - redis-cluster-3
    networks: 
      - sentinel-master-slave  

  # 哨兵节点一号
  redis-cluster-7:
    image: redis:5-alpine
    container_name: redis-cluster-sentinel-1
    ports:
      - 26407:26379
    volumes:
      - ./database/redis-cluster-7:/data
      - ./conf/redis-cluster-7/redis.conf:/etc/redis.conf:rw
      - ./conf/redis-cluster-7/sentinel.conf:/etc/sentinel.conf:rw
    working_dir: /data
    restart: always
    links:
      - redis-cluster-1:redis-master
    networks: 
      - sentinel-master-slave

  # 哨兵节点二号
  redis-cluster-8:
    image: redis:5-alpine
    container_name: redis-cluster-sentinel-2
    ports:
      - 26408:26379
    volumes:
      - ./database/redis-cluster-8:/data
      - ./conf/redis-cluster-8/redis.conf:/etc/redis.conf:rw
      - ./conf/redis-cluster-8/sentinel.conf:/etc/sentinel.conf:rw
    working_dir: /data
    restart: always
    links:
      - redis-cluster-1:redis-master
    networks: 
      - sentinel-master-slave  

  # 哨兵节点三号
  redis-cluster-9:
    image: redis:5-alpine
    container_name: redis-cluster-sentinel-3
    ports:
      - 26409:26379
    volumes:
      - ./database/redis-cluster-9:/data
      - ./conf/redis-cluster-9/redis.conf:/etc/redis.conf:rw
      - ./conf/redis-cluster-9/sentinel.conf:/etc/sentinel.conf:rw
    working_dir: /data
    restart: always
    links:
      - redis-cluster-1:redis-master
    networks: 
      - sentinel-master-slave    

# 网络配置
networks:
  sentinel-master-slave: