version: '3'

services:

  # 节点一号
  redis-cluster-1:
    image: redis:5-alpine
    container_name: redis-cluster-1
    ports:
      - 6401:6379
    volumes:
      - ./database/redis-cluster-1:/data
      - ./conf/redis-cluster-1/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    networks:
      - redis-cluster

  # 节点二号
  redis-cluster-2:
    image: redis:5-alpine
    container_name: redis-cluster-2
    ports:
      - 6402:6379
    volumes:
      - ./database/redis-cluster-2:/data
      - ./conf/redis-cluster-2/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    links:
      - redis-cluster-1
    depends_on:
      - redis-cluster-1
    networks:
      - redis-cluster

  # 节点三号
  redis-cluster-3:
    image: redis:5-alpine
    container_name: redis-cluster-3
    ports:
      - 6403:6379
    volumes:
      - ./database/redis-cluster-3:/data
      - ./conf/redis-cluster-3/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    links:
      - redis-cluster-1
    depends_on:
      - redis-cluster-2
    networks:
      - redis-cluster

  # 节点四号
  redis-cluster-4:
    image: redis:5-alpine
    container_name: redis-cluster-4
    ports:
      - 6404:6379
    volumes:
      - ./database/redis-cluster-4:/data
      - ./conf/redis-cluster-4/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    links:
      - redis-cluster-1
    depends_on:
      - redis-cluster-3
    networks:
      - redis-cluster

  # 节点五号
  redis-cluster-5:
    image: redis:5-alpine
    container_name: redis-cluster-5
    ports:
      - 6405:6379
    volumes:
      - ./database/redis-cluster-5:/data
      - ./conf/redis-cluster-5/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    links:
      - redis-cluster-1
    depends_on:
      - redis-cluster-4
    networks:
      - redis-cluster

  # 节点六号
  redis-cluster-6:
    image: redis:5-alpine
    container_name: redis-cluster-6
    ports:
      - 6406:6379
    volumes:
      - ./database/redis-cluster-6:/data
      - ./conf/redis-cluster-6/redis.conf:/etc/redis.conf:rw
    working_dir: /data
    entrypoint: ['redis-server', '/etc/redis.conf']
    restart: always
    links:
      - redis-cluster-1
    depends_on:
      - redis-cluster-5
    networks:
      - redis-cluster

# 网络配置
networks:
  redis-cluster: