version: "3"

services:
  redis-cluster-1:
    image: redis:5-alpine
    container_name: redis-cluster-master-1
    ports:
      - 6401:6379
    volumes:
      - ./database/redis-cluster-1:/data
      - ./conf/redis-cluster-1/redis.conf:/etc/redis.conf:ro
    working_dir: /data
    environment:
      - REDIS_PASSWORD=123456
    entrypoint: ["redis-server", "/etc/redis.conf"]
    restart: always
    networks: 
      - default
  redis-cluster-2:
    image: redis:5-alpine
    container_name: redis-cluster-master-2
    ports:
      - 6402:6379
    volumes:
      - ./database/redis-cluster-2:/data
      - ./conf/redis-cluster-2/redis.conf:/etc/redis.conf:ro
    working_dir: /data
    environment:
      - REDIS_PASSWORD=123456
    entrypoint: ["redis-server", "/etc/redis.conf"]
    restart: always
    networks: 
      - default
                 

  redis-cluster-3:
    image: redis:5-alpine
    container_name: redis-cluster-master-3
    ports:
      - 6403:6379
    volumes:
      - ./database/redis-cluster-3:/data
      - ./conf/redis-cluster-3/redis.conf:/etc/redis.conf:ro
    working_dir: /data
    environment:
      - REDIS_PASSWORD=123456
    entrypoint: ["redis-server", "/etc/redis.conf"]
    restart: always
    networks: 
      - default

  redis-cluster-4:
    image: redis:5-alpine
    container_name: redis-cluster-slave-1
    ports:
      - 6404:6379
    volumes:
      - ./database/redis-cluster-4:/data
      - ./conf/redis-cluster-4/redis.conf:/etc/redis.conf:ro
    working_dir: /data
    environment:
      - REDIS_PASSWORD=123456
    entrypoint: ["redis-server", "/etc/redis.conf"]
    restart: always
    depends_on:
      - redis-cluster-1
    networks: 
      - default

  redis-cluster-5:
    image: redis:5-alpine
    container_name: redis-cluster-slave-2
    ports:
      - 6405:6379
    volumes:
      - ./database/redis-cluster-5:/data
      - ./conf/redis-cluster-5/redis.conf:/etc/redis.conf:ro
    working_dir: /data
    environment:
      - REDIS_PASSWORD=123456
    entrypoint: ["redis-server", "/etc/redis.conf"]
    restart: always
    depends_on:
      - redis-cluster-2
    networks: 
      - default         

  redis-cluster-6:
    image: redis:5-alpine
    container_name: redis-cluster-slave-3
    ports:
      - 6406:6379
    volumes:
      - ./database/redis-cluster-6:/data
      - ./conf/redis-cluster-6/redis.conf:/etc/redis.conf:ro
    working_dir: /data
    environment:
      - REDIS_PASSWORD=123456
    entrypoint: ["redis-server", "/etc/redis.conf"]
    restart: always
    depends_on:
      - redis-cluster-3
    networks: 
      - default               
networks:
  default: